/**
 * Reference case FP-01 for the face-pressure module tests.
 *
 * Expected values generated by scripts/gen_face_reference.py — an INDEPENDENT
 * implementation written directly from ASCE 36-15 §13.4, not ported from the
 * TypeScript. Countersign with a hand calc before closing U8.
 */
import type { FaceInputs } from './types';

const STATION_COMMON = { gammaPcf: 125, k0: 0.45, ka: 0.28 };

export const FP01_INPUTS: FaceInputs = {
  pipeODIn: 48,
  cutterODIn: 49.5,
  targetBasis: 'at-rest',
  blowoutFactor: 1.0,
  stations: [
    { stationFt: 0, coverFt: 8, gwAboveAxisFt: 2, ...STATION_COMMON },
    { stationFt: 150, coverFt: 12, gwAboveAxisFt: 6, ...STATION_COMMON },
    { stationFt: 300, coverFt: 15, gwAboveAxisFt: 9, ...STATION_COMMON },
    { stationFt: 450, coverFt: 20, gwAboveAxisFt: 14, ...STATION_COMMON },
    { stationFt: 600, coverFt: 25, gwAboveAxisFt: 20, ...STATION_COMMON },
  ],
};

export const FP01_EXPECTED = {
  uPsf: [124.8, 374.4, 561.6, 873.6, 1248.0],
  sigmaVEffPsf: [1125.2, 1375.6, 1563.4, 1876.4, 2127.0],
  sigmaVTotalPsf: [1250.0, 1750.0, 2125.0, 2750.0, 3375.0],
  minStablePsf: [439.856, 759.568, 999.352, 1398.992, 1843.56],
  targetPsf: [631.14, 993.42, 1265.13, 1717.98, 2205.15],
  maxBlowoutPsf: [1250.0, 1750.0, 2125.0, 2750.0, 3375.0],
  targetForceKips: [8.434581, 13.276105, 16.907249, 22.959155, 29.469714],
  governingTargetPsf: 2205.15,
  governingStationFt: 600,
};
