/**
 * Reference case REF-01 for the jacking engine tests.
 *
 * Expected values generated by scripts/gen_reference.py — an INDEPENDENT
 * implementation written directly from ASCE 36-15 §13.4/§13.3/§16.5, not ported
 * from the TypeScript. Countersign with a hand calc before closing U7.
 */
import type { JackingInputs } from './types';

export const REF01_INPUTS: JackingInputs = {
  pipeODIn: 48,
  cutterODIn: 49.5,
  faceBasis: 'at-rest',
  groundClasses: [{ cls: 'MedDenseSand', fLowPsf: 150, fBasePsf: 250, fHighPsf: 400 }],
  segments: [
    {
      startFt: 0, endFt: 200, groundCls: 'MedDenseSand', gammaPcf: 125,
      coverFt: 15, gwAboveAxisFt: 6, k0: 0.45, frictionMode: 'tabulated',
      curveFactor: 1, include: true,
    },
    {
      startFt: 200, endFt: 450, groundCls: 'MedDenseSand', gammaPcf: 128,
      coverFt: 18, gwAboveAxisFt: 9, k0: 0.45, frictionMode: 'arching',
      phiResidualDeg: 30, cohesionPsf: 0, lubricationReduction: 0.8,
      curveFactor: 1, include: true,
    },
    {
      startFt: 450, endFt: 600, groundCls: 'MedDenseSand', gammaPcf: 130,
      coverFt: 20, gwAboveAxisFt: 10, k0: 0.5, frictionMode: 'buoyant',
      pipeBuoyantWeightPlf: 420, muPrime: 0.35, curveFactor: 1.15,
      include: true,
    },
  ],
  restartLow: 1.0,
  restartBase: 1.15,
  restartHigh: 1.3,
  capacities: [{ name: 'Pipe / joint system', capacityKips: 1200, owner: 'Pipe manufacturer' }],
  ijsCapacityKips: 900,
  warnUtilization: 0.85,
};

export const REF01_EXPECTED = {
  segFaceKips: [15.531287, 19.52326, 23.280159],
  segFricLowKips: [376.991118, 662.051769, 25.3575],
  segFricBaseKips: [628.318531, 662.051769, 25.3575],
  segFricHighKips: [1005.309649, 662.051769, 25.3575],
  segTotalLowKips: [392.522406, 1058.566147, 1087.680546],
  segTotalBaseKips: [740.42729, 1506.377593, 1539.859152],
  segTotalHighKips: [1327.093217, 2192.950081, 2230.7988],
  archingSigmaNPsf: 456.2603,
  archingMuPrime: 0.46188,
  maxFaceKips: 23.280159,
  maxHighKips: 2230.7988,
  maxBaseKips: 1539.859152,
  maxFricRateHighKpf: 6.534513,
  driveLengthFt: 600,
  ijsFirstStationFt: 133.098799,
  ijsSpacingFt: 137.730239,
  ijsCount: 5,
  pushbackKips: 30.264207, // maxFaceKips × restartHigh
  pipeUtilHigh: 2230.7988 / 1200,
};
