/**
 * Reference case ST-01 for the settlement module tests.
 *
 * Expected values generated by scripts/gen_settlement_reference.py — an
 * INDEPENDENT implementation of the Peck trough method (ASCE 36-15 §13.5),
 * not ported from the TypeScript. Countersign with a hand calc before
 * closing U9.
 *
 * NOTE: VL = 1.5% is deliberately below the geometric overcut annulus (5.97%)
 * to exercise the unconservative-volume-loss warning.
 */
import type { SettlementInputs } from './types';

export const ST01_INPUTS: SettlementInputs = {
  cutterODIn: 49.5,
  pipeODIn: 48,
  volumeLossPct: 1.5,
  settleLimitIn: 0.5,
  slopeLimitDenom: 500,
  segments: [
    { startFt: 0, endFt: 200, groundCls: 'stiff clay', coverFt: 12, kParam: 0.5, include: true },
    { startFt: 200, endFt: 450, groundCls: 'dense sand', coverFt: 18, kParam: 0.4, include: true },
    { startFt: 450, endFt: 600, groundCls: 'stiff clay', coverFt: 10, kParam: 0.5, include: true },
  ],
  receptors: [
    { name: 'House A', stationFt: 500, offsetFt: 10 },
    { name: 'Gas main', stationFt: 100, offsetFt: 5 },
  ],
};

export const ST01_EXPECTED = {
  excavatedAreaFt2: 13.364041,
  vsFt2PerFt: 0.200461,
  annulusVolumeLossPct: 5.9688,
  z0Ft: [14.0, 20.0, 12.0],
  iFt: [7.0, 8.0, 6.0],
  sMaxIn: [0.137095, 0.119958, 0.159944],
  maxSlope: [0.00098991, 0.0007579, 0.00134738],
  govIdx: 2,
  maxSettleIn: 0.159944,
  houseASettleIn: 0.039882,
  houseASlope: 0.00092321,
  gasMainSettleIn: 0.106227,
  gasMainSlope: 0.00090329,
};
